site_name: Using Vim 9 with Lean
repo_name: gitlab<br>castedo/vim9-lean
repo_url: https://gitlab.com/castedo/vim9-lean
edit_uri: -/edit/website/docs
site_url: https://vim.castedo.com
theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - toc.integrate
    - navigation.footer
    - navigation.top
    - navigation.tracking
  logo: style/vimlogo.svg
  favicon: style/vim_document_icon.jpg
extra_css:
  - style/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - def_list
nav:
  - Home: index.md
  - Install: install.md
  - vim9-lean: vim9-lean.md
  - Key mappings: key-mappings.md
  - Generic LSP: lsp.md
  - Applications: applications.md
  - InfoView: infoview.md
  - About: about.md
not_in_nav: |
  math-input.md
extra:
  generator: false
copyright: '<a href="/about/">About</a>'
